FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_EMBY_SERVER_URL
ARG VITE_EMBY_API_KEY
ARG VITE_EMBY_ACCESS_TOKEN
ARG VITE_EMBY_USER_ID
ARG VITE_EMBY_LIBRARY_ID
ARG VITE_EMBY_LIBRARY_NAME

ENV VITE_EMBY_SERVER_URL=$VITE_EMBY_SERVER_URL
ENV VITE_EMBY_API_KEY=$VITE_EMBY_API_KEY
ENV VITE_EMBY_ACCESS_TOKEN=$VITE_EMBY_ACCESS_TOKEN
ENV VITE_EMBY_USER_ID=$VITE_EMBY_USER_ID
ENV VITE_EMBY_LIBRARY_ID=$VITE_EMBY_LIBRARY_ID
ENV VITE_EMBY_LIBRARY_NAME=$VITE_EMBY_LIBRARY_NAME

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
